<?php

/**
 * @file
 * Differences notification
 * Simple way of notifying (by email) a configurable list of users,
 * upon modification of nodes from a configurable list of content types.
 * 
 * Use case :
 * A list of users must always be notified by email
 * when any content of a list of content types is modified by someone else,
 * and they must receive the list of modifications (see required 'diff' module).
 * 
 * Restrictions :
 *  • Single list of subscribers (no too many ~ 20 max maybe,
 *    because there is no queue for sending emails)
 *  • Single list of content types
 *  • Only triggers on modification of these nodes
 *  • No exceptions, no conditions
 * 
 * Alternatives :
 *  • Comparison of notifications / subscriptions modules :
 *    @see https://groups.drupal.org/node/15928
 *  • Message stack :
 *    @see http://drupal.org/project/message
 */


/**
 * Implement hook_node_update()
 */
function diffnotif_node_update($node) {
  $content_types_whitelist = explode(',',variable_get('diffnotif_content_types', ''));
  $subscribers_uids = explode(',',variable_get('diffnotif_subscribers', ''));
  if (empty($content_types_whitelist) || empty($subscribers_uids)) {
    return;
  }
  if (in_array($node->type, $content_types_whitelist)) {
    $path = drupal_get_path('module', 'diff');
    module_load_include('inc', 'diff', 'diff.pages');
    
    // Create diff of old node and edited node.
    $rows = _diff_body_rows($node->original, $node);
    $header = _diff_default_header(t('Original'), t('Changes'));
    $diff_markup = theme('table__diff__preview', array(
      'header' => $header,
      'rows' => $rows,
      'attributes' => array('class' => 'diff'),
      'colgroups' => _diff_default_cols(),
      'sticky' => FALSE,
    ));
    
    // debug ok 2014/08/13 15:55:35
    //drupal_set_message("<style>" . file_get_contents("$path/diff.css") . "</style>");
    //drupal_set_message("<style>" . file_get_contents("$path/css/diff.default.css") . "</style>");
    //drupal_set_message($diff_markup);
    
    // Email content
    // @todo i18n - use t() for text
    global $user;
    $recipients = array();
    $message_body = "";
    $message_subject = "Notif Modif " . $node->type . ' : "' . $node->original->title . '" by ' . $user->name;
    $message_body .= "<style>";
    $message_body .= file_get_contents("$path/diff.css");
    $message_body .= file_get_contents("$path/css/diff.default.css");
    $message_body .= "</style>";
    $message_body .= "By : <strong>";
    $message_body .= $user->name;
    $message_body .= " (";
    $message_body .= $user->mail;
    $message_body .= ")</strong>";
    $message_body .= "<br/>";
    $message_body .= "Date : <strong>";
    $message_body .= format_date(time());
    $message_body .= "</strong><br/>";
    $message_body .= "Details :";
    $message_body .= "<br/>";
    $message_body .= $diff_markup;
    $message_body .= "<br/>";
    
    // Recipients
    foreach($subscribers_uids as $uid) {
      if ($user->uid != $uid) {
        $account = user_load($uid);
        $recipients[] = $account->name . ' <' . $account->mail . '>';
      }
    }
    
    // Send email
    drupal_mail('diffnotif', 'notif', join(', ', $recipients), language_default(), array(
      'subject' => $message_subject,
      'body' => $message_body,
    ));
  }
}


/**
 * Implement hook_menu()
 */
function diffnotif_menu() {
  $items = array();

  $items['admin/config/diffnotif'] = array(
    'title' => t("Differences notification"),
    'description' => t('Simple way of notifying (by email) a configurable list of users, upon modification of nodes from a configurable list of content types.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('diffnotif_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'diffnotif.admin.inc',
  );

  return $items;
}


/**
 * Implement hook_mail()
 */
function diffnotif_mail($key, &$message, $params) {
  switch($key) {
    default :
    case 'notif' :
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      break;
  }
}

